apiVersion: v1
kind: Service
metadata:
  name: {{ include "hr-skill-matrix.fullname" . }}-app-service
  labels:
    app: skill-matrix-app
  {{- include "hr-skill-matrix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.appService.type }}
  selector:
    app: skill-matrix-app
    {{- include "hr-skill-matrix.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.appService.ports | toYaml | nindent 2 }}
