{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hr-skill-matrix.fullname" . }}-auth-credentials
  labels:
    {{- include "hr-skill-matrix.labels" . | nindent 4 }}
type: Opaque
data:
  OIDC_CLIENT_SECRET: {{ .Values.auth.oidc.clientSecret | b64enc | quote }}
{{- end }}
