apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hr-skill-matrix.fullname" . }}-db-credentials
  labels:
  {{- include "hr-skill-matrix.labels" . | nindent 4 }}
data:
  DB_DATABASE: {{ required "dbCredentials.dbDatabase is required" .Values.mariadb.auth.database
    | b64enc | quote }}
  DB_PASSWORD: {{ required "dbCredentials.dbPassword is required" .Values.mariadb.auth.password
    | b64enc | quote }}
  DB_USER: {{ required "dbCredentials.dbUser is required" .Values.mariadb.auth.username
    | b64enc | quote }}
type: Opaque
