apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hr-skill-matrix.fullname" . }}-db-credentials
  labels:
    app: skill-matrix-app
  {{- include "hr-skill-matrix.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.mariadb.auth.username | quote }}
  DB_PASSWORD: {{ .Values.mariadb.auth.password | quote }}
  DB_DATABASE: {{ .Values.mariadb.auth.database | quote }}