apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hr-skill-matrix.fullname" . }}-db-credentials
type: Opaque
stringData:
  DATABASE_URL: mysql+mysqlconnector://{{ .Values.mariadb.auth.username }}:{{ .Values.mariadb.auth.password }}@{{ .Release.Name }}-mariadb:3306/{{ .Values.mariadb.auth.database }}