apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hr-skill-matrix.fullname" . }}-app-deployment
  labels:
    app: skill-matrix-app
  {{- include "hr-skill-matrix.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.appDeployment.replicas }}
  selector:
    matchLabels:
      app: skill-matrix-app
    {{- include "hr-skill-matrix.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: skill-matrix-app
      {{- include "hr-skill-matrix.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "hr-skill-matrix.fullname" . }}-db-credentials
              key: DATABASE_URL
        image: {{ .Values.appDeployment.skillMatrixApp.image.repository }}:{{ .Values.appDeployment.skillMatrixApp.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.appDeployment.skillMatrixApp.imagePullPolicy }}
        name: skill-matrix-app
        ports:
        - containerPort: 8000
        resources: {{- toYaml .Values.appDeployment.skillMatrixApp.resources | nindent
          10 }}
      initContainers:
      - name: wait-for-mariadb
        image: {{ .Values.appDeployment.waitForMariadb.image.repository }}:{{ .Values.appDeployment.waitForMariadb.image.tag | default .Chart.AppVersion }}
        command:
        - sh
        - -c
        - |
          echo "Waiting for MariaDB at {{ .Release.Name }}-mariadb:3306..."
          until nc -z {{ .Release.Name }}-mariadb 3306; do
            echo "MariaDB not ready yet, sleeping..."
            sleep 2
          done
          echo "MariaDB is up!"
        resources: {}
